const Home = () => {
    return (
        <div className="container">
        <h1 className="title">CO2-footprint</h1>
        <p className="info">A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.
        Globally, the average carbon footprint is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year needs to drop to under 2 tons by 2050.
    </p>
        </div>
    )
    
};
  
  export default Home;