import Sidebar from './components/Sidebar'

function App() {
  return (
    <div className="main">
      <Sidebar />
      <div className="container">
        <h1 className="title">Carbon footprint</h1>
        <p className="info">A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.
</p>
        <button className="btn">Explore now</button>
      </div>
    </div>
  )
}

export default App
